version: '2'
services:
    test:
        image: silintl/php7-apache:7.4.19
        env_file:
          - local.env
        volumes:
            - ./:/data/
        working_dir: /data
        command: vendor/bin/behat
