version: '2'
services:
    test:
        image: php:7.4-apache
        env_file:
          - local.env
        volumes:
            - ./:/data/
        working_dir: /data
        command: vendor/bin/behat
